### ISSUE TITLE
articleFeed page do not access

### ISSUE THREAD

**Issue by patrickpeng2091** [BioPhoton/ng-drupal-7-services#13]
hi, @BioPhoton

I use ng-drupal-7-services 2.10
but , my article page do not access
![image](https://cloud.githubusercontent.com/assets/4326820/13903425/a0183478-eeb5-11e5-9ecc-a14e843313c7.png)

**Comment by patrickpeng2091** [comment]
how to config  image path ?
sites/default/files  ?

**Comment by BioPhoton** [comment]
Hi @patrick-peng,
Could you post some of your code? I'm not shure if i understand you.

**Comment by patrickpeng2091** [comment]
articleFeed.service.js

`    function prepareArticle(article) {
      angular.forEach(article.field_image.und, function (value, key) {

```
    article.field_image.und[key].imgPath = DrupalHelperService.getPathToImgByStyle(DrupalApiConstant.imageStyles.medium) + article.field_image.und[key].uri.split('//')[1];
    article.nid = parseInt(article.nid);
  });

  article.nid = parseInt(article.nid);

  return article;
};`
```

**Comment by patrickpeng2091** [comment]
![image](https://cloud.githubusercontent.com/assets/4326820/13921193/b0ec151a-efb1-11e5-97e5-08a5b5ed5b9e.png)
my image path.
http://1035.dd:8084/sites/default/files/styles/medium/public/styles/medium/public/ad2_3.png

i see your web demo ,http://www.drupalionic.org/app_demo/index.html
The image path : sites/default/files/styles/large/public/public/drupal_1.jpg

how config image path ?

**Comment by patrickpeng2091** [comment]
@BioPhoton I have another question to ask you. 

The  testview views ,If sorting category is not working,How to specify category ？

**Comment by patrickpeng2091** [comment]
I do not have to modify the logic code, I just modified some ionic ui.

**Comment by BioPhoton** [comment]
Hi, @patrick4u.

I will open a new issue for the image path problem in this repo.
For the other one related to the article view i will opne a new issue in the [demo project](https://github.com/BioPhoton/Ionic-Angular-Headless-Drupal-Demo) because there is no actice service in this repo.

**Comment by BioPhoton** [comment]
could you please  post your json response from the server to this [issue](https://github.com/BioPhoton/Ionic-Angular-Headless-Drupal-Demo/issues/14)
