### ISSUE TITLE
How to configure the path of an image?

### ISSUE THREAD

**Issue by BioPhoton** [BioPhoton/ng-drupal-7-services#14]
Split of form issue #13.

**Comment by BioPhoton** [comment]
Hi @patrick4u
I released a new version including some change in the getPathToImageByStyle function as well as additional options in the DlupalApiConstant. 

I also added dock for this changes in the [API Documentation](http://www.drupalionic.org/docs) under Commons Helper service and DrupalAPIConstant.

Are you now able to manage the configuration of image stlye paths?

**Comment by patrickpeng2091** [comment]
hi, @BioPhoton , thanks

![image](https://cloud.githubusercontent.com/assets/4326820/14035365/43ca514a-f268-11e5-8820-1822b8c6af0c.png)
![image](https://cloud.githubusercontent.com/assets/4326820/14035372/661b187e-f268-11e5-931c-d57637b90429.png)

**Comment by patrickpeng2091** [comment]
![image](https://cloud.githubusercontent.com/assets/4326820/14035509/08ed79ba-f26a-11e5-8b91-d510b73f6b38.png)

**Comment by BioPhoton** [comment]
In your path i see there is a double slash at public//.

Could you post the full json response and no image please?

**Comment by patrickpeng2091** [comment]
![image](https://cloud.githubusercontent.com/assets/4326820/14036970/9fd82b2c-f279-11e5-8d4b-a1e4113624bb.png)

default path is the sites/default/files ,
my image path is http://m.oucart.com/sites/default/files/ad2_9.png

later ,i found Drupal Devel content generated  image is "//"

if my default path is  sites/default/files 
How do I set up
`//Override the default public and private folders
    DrupalApiConstant.publicFilePath = "";
    DrupalApiConstant.privateFilePath = "";

```
//Override the Drupals default path to files.
DrupalApiConstant.filesPath = "sites/default/files/";

//Override the Drupals default image styles path.
DrupalApiConstant.imageStylesPath = "";

//Override the default image styles and add custom once.
DrupalApiConstant.imageStyles.large = 'modified_large';
DrupalApiConstant.imageStyles.new_style = 'new_style_name';`
```

**Comment by BioPhoton** [comment]
To set up you drupal you should just change drupal_inatance path. Rest should be default.

To generate a path to you image (http://m.oucart.com/sites/default/files/styles/medium/public/ad2_5.png)  you should chack following:

``` javascript
console.log(DrupalApiConstant.drupal_instance); // should result in "http://m.oucart.com/"
console.log(DrupalApiConstant.imageStylesPath ); // should result in "styles/"
console.log(DrupalApiConstant.filesPath); // should result in "sites/default/files/"

var pathToImg = DrupalHelperService.getPathToImgByStyle("medium") + "ad2_5.png";

console.log(pathToImg); // should result in http://m.oucart.com/sites/default/files/styles/medium/public/ad2_5.png); 
```

**Comment by BioPhoton** [comment]
i also relesed a new version of [Ionic Demo](https://github.com/BioPhoton/Ionic-Angular-Headless-Drupal-Demo) with small changes in articleFeed service.

**Comment by patrickpeng2091** [comment]
thanks, 

fix this `DrupalApiConstant.publicFilePath = "../";`

I can see the picture

**Comment by patrickpeng2091** [comment]
@BioPhoton   I want to change the next display HTML, how need to modify ? 
![image](https://cloud.githubusercontent.com/assets/4326820/14063430/4e1659f4-f403-11e5-861c-bcebef70daf7.png)

**Comment by BioPhoton** [comment]
Use Ng-bind-html.

Will close this issue now as o guess the path problem is solved
