### ISSUE TITLE
Task 'compile' is not in your gulpfile (v2.2.1)

### ISSUE THREAD

**Issue by asanchez75** [BioPhoton/ng-drupal-7-services#15]
Task 'compile' is not in your gulpfile

solution

Add

gulp.task('default', ['bundle']);

to your gulpfile.js

**Comment by BioPhoton** [comment]
THX! Will fix it as soon as possible.

**Comment by Grienauer** [comment]
Gr8

Von meinem iPhone gesendet

**Comment by BioPhoton** [comment]
Fixed, sry for the delay
