### ISSUE TITLE
Multiple files

### ISSUE THREAD

**Issue by CaceresBretti** [BioPhoton/ng-drupal-7-services#17]
How can i upload multiple files with this resource?
Great work btw!

Edit: I can upload the files but I can't associate them to one field with multiple values or with n different field at the same request.

**Comment by BioPhoton** [comment]
Hi!
The Workflow should be as follow:
1. Upload file
2. Update node/entoty

If you want to Update the node with multiple Files, you have to send (post or put) all fid's to the node.

Let me know if this helps..

**Comment by CaceresBretti** [comment]
Thank you very much Sir.

Good Day!!
