### ISSUE TITLE
this lib still work?

### ISSUE THREAD

**Issue by liquidcms** [BioPhoton/ng-drupal-7-services#20]
Anyone know if this library is still functional? The README does not seem very Ionic like as NPM is not correct way to install this and bower install fails with:

fatal: HttpRequestException encountered.
   An error occurred while sending the request.
remote: Repository not found.
fatal: repository 'https://github.com/yabasha/angular-messages.git/' not found

Is this lib for Ionic 1 or 2 (or something else)?

Does anyone know of a working lib for Ionic 1 or 2 which provides Drupal interface?

**Comment by BioPhoton** [comment]
Its for ionic 1 and should still work. Didn't used ot for ages... 😊
